openapi: "3.0.2"
info:
  title: WalkAware Trento API
  version: "1.0"
servers:
  - url: http://localhost:3000/api/v1
    description: Localhost
paths:
  /utente/mobile:
    post:
      summary: Create a new mobile user.
      description: Endpoint to create a user from a mobile app.
      tags:
        - UtenteMobile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UtenteMobileRegistrazione"
      responses:
        "201":
          description: User created. Link in Location header.
          headers:
            Location:
              schema:
                type: string
              description: Link to the newly created mobile user.
        "400":
          description: Bad request, invalid body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /utente/mobile/login:
    post:
      summary: Mobile user login
      description: Endpoint for mobile user login.
      tags:
        - UtenteMobile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UtenteLogin"
      responses:
        "200":
          description: Successful login.
          headers:
            Location:
              schema:
                type: string
              description: Link to the logged-in user.
        "401":
          description: Invalid Credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /utente/mobile/{id}/punti:
    get:
      summary: Get mobile user personal points
      description: Endpoint for mobile user to get personal points
      tags:
        - UtenteMobile
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: mobile user ID
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UtenteMobilePuntiBody"
        "404":
          description: User not found by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update mobile user personal points
      description: Endpoint for mobile user to get personal points
      tags:
        - UtenteMobile
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: mobile user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UtenteMobilePuntiBody"
      responses:
        "200":
          description: Successful request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UtenteMobilePuntiBody"
        "404":
          description: User not found by id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"    
        "400":
          description: Bad request, invalid body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"      

  /utente/web:
    post:
      summary: Create a new web user.
      description: Endpoint to create a user from a web app.
      tags:
        - UtenteWeb
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UtenteWebRegistrazione"
      responses:
        "201":
          description: User created. Link in Location header.
          headers:
            Location:
              schema:
                type: string
              description: Link to the newly created web user.
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /utente/web/login:
    post:
      summary: Web user login
      description: Endpoint for web user login.
      tags:
        - UtenteWeb
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UtenteLogin"
      responses:
        "200":
          description: Successful login.
          headers:
            Location:
              schema:
                type: string
              description: Link to the logged-in user.
        "401":
          description: Invalid Credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    UtenteMobileRegistrazione:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        nome:
          type: string
        eta:
          type: string
      required:
        - password
        - email
        - nome
        - eta

    UtenteLogin:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - password
        - email

    UtenteMobilePuntiBody:
      type: object
      properties:
        punti:
          type: number

    UtenteWebRegistrazione:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        nome:
          type: string
      required:
        - password
        - email
        - nome

    Error:
      type: object
      properties:
        error:
          type: string
