name: walkaware
description: "Cammina per Trento e aiuta a migliorare la città!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  mapbox_maps_flutter: ^2.0.0-beta.1
  mapbox_search: ^4.2.2
  modal_bottom_sheet: ^3.0.0
  geolocator:
  dio: ^5.4.3+1
  intl: ^0.19.0
  url_launcher: ^6.2.6
  date_field: ^5.0.1
  crypt: ^4.3.1
  android_intent_plus: ^5.0.2
  pedometer: ^4.0.1
  material_symbols_icons: ^4.2719.3
  flutter_activity_recognition: ^3.0.0
  introduction_screen: ^3.1.14
  dots_indicator: ^2.1.2
  dart_jsonwebtoken: ^2.14.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  turf: ^0.0.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: '#69A84F'
  adaptive_icon_foreground: "assets/icon.png"
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#69A84F"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
